name: express-api-server

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: express-api-server
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app # 掛載專案
      - /app/node_modules # 停止掛載到本地的 node_modules
      - /app/db # 停止掛載到本地的 db
      - ./uploads:/app/uploads
    networks:
      - express-api-server-network

networks:
  express-api-server-network:
    driver: bridge
